### PR TITLE
 debian/*: Fix DEB builds (GTK-3+ only for now) after CMake switch-over.

### PR DESCRIPTION
**Pull request by sunweaver**

### CODE REVIEW

**Comment by sunweaver** [comment]
@tari01: please review #25 first, merge it, then rebase this PR branch, then merge this (#26). Thanks.

**Comment by sunweaver** [comment]
urgh??? Why close?

**Comment by sunweaver** [comment]
Please rebase this PR branch against master, push the rebased PR branch and then merge.

**Comment by sunweaver** [comment]
ah, merged, but in a way that did not close this PR... you always have to update the PR branch with the local rebased version. Otherwise Github won't realize that your rebased push should close it.

**Comment by ghost** [comment]
> ah, merged, but in a way that did not close this PR... you always have to update the PR branch with the local rebased version. Otherwise Github won't realize that your rebased push should close it.

I did not know GitHub had this "feature" of not realising a rebased PR was just pushed. It's smart enough to connect the commit to the PR, but does nothing about it. Now I know it won't work without force-pushing it back.

**Pull request closed without merging**
