### PR TITLE
src/app-indicator.c: Avoid usage of PATH_MAX macro. Fixes FTBFS on De…

### PR DESCRIPTION
**Pull request by sunweaver**
…bian GNU/Hurd.

### CODE REVIEW

**Comment by sunweaver** [comment]
@sthibaul: Here is a fix-up for an FTBFS of lib(ayatana-)appindicator on GNU/Hurd. Could you check, if my patch is a valid fix for yet another PATH_MAX issue. THANKS!

**Comment by sthibaul** [comment]
It's a valid approach, yes

**Comment by jrtc27** [comment]
Aren't you now leaking `canon_path`? `canonicalize_file_name` returns a dynamically-allocated buffer that needs to be freed, and you either return `g_strdup(canon_path)` or `g_build_path(..., canon_path, canon_path)`, without freeing `canon_path` itself (previously `real_path` was stack-allocated and therefore did not need feeing).

**Comment by sunweaver** [comment]
Nice! Thanks for taking a look.
Mike

On Friday, October 6, 2017, Samuel Thibault wrote:
> It's a valid approach, yes 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.￼
>

-- 
Sent from my Fairphone (running Sailfish OS)...

**Comment by sunweaver** [comment]
On  Fr 06 Okt 2017 19:52:02 CEST, James Clarke wrote:

> Aren't you now leaking `canon_path`? `canonicalize_file_name`  
> returns a dynamically-allocated buffer that needs to be freed, and  
> you either return `g_strdup(canon_path)` or `g_build_path(...,  
> canon_path, canon_path)`, without freeing `canon_path` itself  
> (previously `real_path` was stack-allocated and therefore did not  
> need feeing).

To my understanding, this should be handled by

```
g_autofree gchar *canon_path = NULL;
```

in the patch.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by jrtc27** [comment]
Oh, interesting, I completely skimmed over that (and wasn't at all expecting it to be there as I am not familiar with GLib), so yes I assume that's fine.

**Comment by sunweaver** [comment]
Cherry-picked as bc7f6838bdffff00f8a752f1ce387d12fcb06ca0. Thus, closing.

**Pull request closed without merging**
